version: '3'
services:
  server_redis_database:
    image: redis:latest
    container_name: server_redis_database
    env_file:
      - .env
    volumes:
      - ./redis_data:/data
    restart: always
    expose:
      - "6379"
    ports:
      - "6379:6379"
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
  mongo-express:
    image: "mongo-express:latest"
    ports:
      - "8081:8081"
  server:
    build : 
      dockerfile : Dockerfile.dev
      context : .
    volumes :
      - /app/node_modules
      - .:/app
    env_file : 
      - .env
    ports:
      - "3000:3000"
